version: '3.7'

services:
  server:
    build:
      context: ./server/backend
      dockerfile: Dockerfile
    volumes:
      - ./server/backend/:/backend/
    command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ./server/backend/.env
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./server/backend/.env
    ports:
      - 5432:5432

  cliente:
    build:
      context: ./client/frontend
      dockerfile: Dockerfile
    volumes:
      - ./client/frontend/:/frontend/
    command: npm start
    ports:
      - 3000:3000

volumes:
    postgres_data:
